version: '3'

services:
  database:
    image: mysql:8.0.35
    container_name: theatredatabase #nom que l'on donne au container qui apparait sur docker
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: theatreprojet #nom de la base de donnée
    volumes:
      - database_data:/var/lib/mysql  
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmintest
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - dev

  www:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile    
    container_name: monsitetheatre
    ports:
      - "8000:80"
    volumes:
      - ./Docker/vhost:/etc/apache2/sites-enabled
      - ./:/var/www
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root 
      DATABASE_PASSWORD: ""
    depends_on:
      - database
    networks:
      - dev  

      
networks:
  dev:
volumes:
  database_data: